version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: hub
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: